menu:
  home: /
  archives: /archives
  about: /about

sidebar_menu:
  categories: /categories
  tags: /tags


# Place your favicon.ico to /source directory.
favicon: /favicon.ico

keywords:
- Hexo
- ninja

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss:

# Widgets:
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Icon fonts
# Place your font into ninja/source/fonts, specify directory-name and font-name here
# Examples: normal | linecons | fifty-shades | feather
icon_font: normal

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night


# MathJax Support
mathjax:


# Analytics
baidu_analytics: 6ea3a6b78cf86228995c577636d3f562


# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true


# Automatically add list number to toc.
toc_list_number: true


# Static files
vendors: vendors
css: css
images: images
js: js


# Theme version
version: 0.0.1
